# Generated by Django 5.0.7 on 2024-07-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0006_remove_player_team_player_teams'),
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='Team.team'),
        ),
    ]
