# Generated by Django 5.0.7 on 2024-07-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0007_remove_player_teams_player_team'),
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='Team.team'),
        ),
    ]
