# Generated by Django 5.0.7 on 2024-07-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='Role',
            new_name='role',
        ),
    ]
