# Generated by Django 5.0.7 on 2024-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_alter_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='img',
            field=models.ImageField(upload_to='manager_images/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='nationality_image',
            field=models.ImageField(null=True, upload_to='manager_nationality_images/'),
        ),
    ]
